export const mockQueue = [
    { id: 1, name: "Player 1", joinedAt: new Date().toISOString() },
    { id: 2, name: "Player 2", joinedAt: new Date().toISOString() },
    { id: 3, name: "Player 3", joinedAt: new Date().toISOString() },
    { id: 4, name: "Player 4", joinedAt: new Date().toISOString() },
    { id: 5, name: "Player 5", joinedAt: new Date().toISOString() },
    { id: 6, name: "Player 6", joinedAt: new Date().toISOString() },
    { id: 7, name: "Player 7", joinedAt: new Date().toISOString() },
    { id: 8, name: "Player 8", joinedAt: new Date().toISOString() },
    { id: 9, name: "Player 9", joinedAt: new Date().toISOString() },
    { id: 10, name: "Player 10", joinedAt: new Date().toISOString() },
    { id: 11, name: "Player 11", joinedAt: new Date().toISOString() },
    { id: 12, name: "Player 12", joinedAt: new Date().toISOString() },
    { id: 13, name: "Player 13", joinedAt: new Date().toISOString() },
    { id: 14, name: "Player 14", joinedAt: new Date().toISOString() },
    { id: 15, name: "Player 15", joinedAt: new Date().toISOString() },
    { id: 16, name: "Player 16", joinedAt: new Date().toISOString() },
    { id: 17, name: "Player 17", joinedAt: new Date().toISOString() },
    { id: 18, name: "Player 18", joinedAt: new Date().toISOString() },
    { id: 19, name: "Player 19", joinedAt: new Date().toISOString() },
    { id: 20, name: "Player 20", joinedAt: new Date().toISOString() },
    { id: 21, name: "Player 21", joinedAt: new Date().toISOString() },
    { id: 22, name: "Player 22", joinedAt: new Date().toISOString() },
    { id: 23, name: "Player 23", joinedAt: new Date().toISOString() },
    { id: 24, name: "Player 24", joinedAt: new Date().toISOString() },
    { id: 25, name: "Player 25", joinedAt: new Date().toISOString() },
    { id: 26, name: "Player 26", joinedAt: new Date().toISOString() },
    { id: 27, name: "Player 27", joinedAt: new Date().toISOString() },
    { id: 28, name: "Player 28", joinedAt: new Date().toISOString() },
    { id: 29, name: "Player 29", joinedAt: new Date().toISOString() },
    { id: 30, name: "Player 30", joinedAt: new Date().toISOString() },
    { id: 31, name: "Player 31", joinedAt: new Date().toISOString() },
    { id: 32, name: "Player 32", joinedAt: new Date().toISOString() },
    { id: 33, name: "Player 33", joinedAt: new Date().toISOString() },
    { id: 34, name: "Player 34", joinedAt: new Date().toISOString() },
    { id: 35, name: "Player 35", joinedAt: new Date().toISOString() },
    { id: 36, name: "Player 36", joinedAt: new Date().toISOString() },
    { id: 37, name: "Player 37", joinedAt: new Date().toISOString() },
    { id: 38, name: "Player 38", joinedAt: new Date().toISOString() },
    { id: 39, name: "Player 39", joinedAt: new Date().toISOString() },
    { id: 40, name: "Player 40", joinedAt: new Date().toISOString() },
  ];
  
  export const mockScores = {
    current: [
      { playerName: "Player 1", score: 85 },
      { playerName: "Player 2", score: 92 },
      { playerName: "Player 3", score: 78 },
      { playerName: "Player 4", score: 95 },
      { playerName: "Player 5", score: 88 },
      { playerName: "Player 6", score: 72 },
      { playerName: "Player 7", score: 91 },
      { playerName: "Player 8", score: 83 },
      { playerName: "Player 9", score: 89 },
      { playerName: "Player 10", score: 77 },
      { playerName: "Player 11", score: 94 },
      { playerName: "Player 12", score: 81 },
      { playerName: "Player 13", score: 88 },
      { playerName: "Player 14", score: 90 },
      { playerName: "Player 15", score: 76 },
      { playerName: "Player 16", score: 82 },
      { playerName: "Player 17", score: 79 },
      { playerName: "Player 18", score: 93 },
      { playerName: "Player 19", score: 84 },
      { playerName: "Player 20", score: 89 },
      { playerName: "Player 21", score: 80 },
      { playerName: "Player 22", score: 92 },
      { playerName: "Player 23", score: 85 },
      { playerName: "Player 24", score: 77 },
      { playerName: "Player 25", score: 90 },
      { playerName: "Player 26", score: 88 },
      { playerName: "Player 27", score: 94 },
      { playerName: "Player 28", score: 78 },
      { playerName: "Player 29", score: 86 },
      { playerName: "Player 30", score: 91 },
      { playerName: "Player 31", score: 83 },
      { playerName: "Player 32", score: 82 },
      { playerName: "Player 33", score: 90 },
      { playerName: "Player 34", score: 77 },
      { playerName: "Player 35", score: 95 },
      { playerName: "Player 36", score: 88 },
      { playerName: "Player 37", score: 81 },
      { playerName: "Player 38", score: 92 },
      { playerName: "Player 39", score: 84 },
      { playerName: "Player 40", score: 80 },
    ],
    accumulated: [
      { playerName: "Player 1", totalScore: 245 },
      { playerName: "Player 2", totalScore: 267 },
      { playerName: "Player 3", totalScore: 234 },
      { playerName: "Player 4", totalScore: 289 },
      { playerName: "Player 5", totalScore: 256 },
      { playerName: "Player 6", totalScore: 219 },
      { playerName: "Player 7", totalScore: 270 },
      { playerName: "Player 8", totalScore: 251 },
      { playerName: "Player 9", totalScore: 264 },
      { playerName: "Player 10", totalScore: 230 },
      { playerName: "Player 11", totalScore: 287 },
      { playerName: "Player 12", totalScore: 243 },
      { playerName: "Player 13", totalScore: 260 },
      { playerName: "Player 14", totalScore: 275 },
      { playerName: "Player 15", totalScore: 221 },
      { playerName: "Player 16", totalScore: 248 },
      { playerName: "Player 17", totalScore: 235 },
      { playerName: "Player 18", totalScore: 285 },
      { playerName: "Player 19", totalScore: 252 },
      { playerName: "Player 20", totalScore: 267 },
      { playerName: "Player 21", totalScore: 245 },
      { playerName: "Player 22", totalScore: 270 },
      { playerName: "Player 23", totalScore: 246 },
      { playerName: "Player 24", totalScore: 228 },
      { playerName: "Player 25", totalScore: 275 },
      { playerName: "Player 26", totalScore: 260 },
      { playerName: "Player 27", totalScore: 291 },
      { playerName: "Player 28", totalScore: 232 },
      { playerName: "Player 29", totalScore: 253 },
      { playerName: "Player 30", totalScore: 268 },
      { playerName: "Player 31", totalScore: 250 },
      { playerName: "Player 32", totalScore: 248 },
      { playerName: "Player 33", totalScore: 276 },
      { playerName: "Player 34", totalScore: 229 },
      { playerName: "Player 35", totalScore: 290 },
      { playerName: "Player 36", totalScore: 257 },
      { playerName: "Player 37", totalScore: 242 },
      { playerName: "Player 38", totalScore: 269 },
      { playerName: "Player 39", totalScore: 254 },
      { playerName: "Player 40", totalScore: 241 },
    ],
  };
  